name: Replicate Commits to Version Branch

on:
  push:
    branches:
      - master

jobs:
  version-branch:
    uses: openwisp/openwisp-utils/.github/workflows/reusable-version-branch.yml@improve-reusable-version-branch
    with:
      module_name: netjsonconfig.version
      install_package: true
